# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b8c71d547c412dcd154dd475228379e3147b166bcd098aa0daee4b5c212efc2cff91e40b84297f72428da6fb520354153041c7e7a1e46d6dbc7e2f7a7c7a964

test:
  secret_key_base: 12c27b3506b8a503d6bea1581924083e49e5fee855f8829d63f8006a396d4db56e93e06397a48306be478c2fb274b23ecd55569980feadd83f5e23c0673d8aa1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
